#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""This is a class for a square with attribute size"""

class Square:

    """This is a square class """

    def __init__(self, size):
        """
        Constructs all the necessary attributes for square

        Parameters
        ----------
        size : int
            the size of square object
        """
        self.__size = size
